### ISSUE TITLE
Plugin with id 'pandoc' not found.

### ISSUE THREAD

**Issue by jsonify** [sleroy/gradle-doc-plugin#2]
After using the snippet provided in the README,
```
buildscript { 
	repositories {
		mavenLocal()
    	jcenter()
    	maven { url 'http://dl.bintray.com/sleroy/maven' }
	}
	dependencies {
    	classpath 'com.metrixware:gradle-doc-plugin:0.1.2+'
	}
}
apply plugin: 'pandoc'
```
 when I run the `gradle pandoc-configure` command, I get the following error:

> Plugin with id 'pandoc' not found.

Just trying to figure out what I'm doing wrong.

**Comment by sleroy** [comment]
Please, have a look on my updated documentation and snippet.

https://github.com/sleroy/gradle-doc-plugin/blob/master/README.md

https://github.com/sleroy/gradle-doc-plugin/tree/master/example

**Comment by sleroy** [comment]
Is it solving the issue ?

**Comment by jsonify** [comment]
Yes, I am able to run the `pandoc-configure` command now with no problems. Thank you.

**Comment by sleroy** [comment]
Is it solving the issue ?
