### ISSUE TITLE
pandoc-check fails standard with Windows setup

### ISSUE THREAD

**Issue by drkstr101** [sleroy/gradle-doc-plugin#3]
https://github.com/sleroy/gradle-doc-plugin/blob/c6c24570545ba6f837d1125d38c97710e6be15d2/src/main/groovy/com/metrixware/gradle/pandoc/project/ToolCheckingTask.groovy#L56

Changing this line:
`ProcessBuilder builder = new ProcessBuilder("${project.documentation.pdfTexBin} -v".split())`

To this:
`ProcessBuilder builder = new ProcessBuilder("${project.documentation.pdfTexBin} --version".split())`

This should work in either environment.

**Comment by sleroy** [comment]
#5 fixed and deployed in version 0.1.4

https://bintray.com/sleroy/maven/gradle-pandoc-plugin/0.1.4
